### ISSUE TITLE
Expand second level of tree in sidebar

### ISSUE THREAD

**Issue by bmaupin** [bmaupin/wiki#20]
At least until #16 is done...

**Comment by bmaupin** [comment]
Hmm, this actually looks a bit meh. Closing for now.

If we decide to change our minds:

1. style.css

   ```css
   /* Hide child items starting at the third level of depth */
   .sidebar-menu .page-tree ul ul ul {
     display: none;
   }
   ```

1. assets/js/page-tree.js

   ```javascript
    if (
      id === 'sidebar-menu' &&
      pageListingLinks[i].parentElement.parentElement.parentElement.nodeName ===
        'LI'
    ) {
      listCollapser.className = 'fas fa-chevron-down list-collapser collapsed';
    } else {
      listCollapser.className = 'fas fa-chevron-down list-collapser expanded';
    }
   ```
